export const sample_habits: any[] = [
  {
    id: '1',
    name: 'pływanie',
    category: ['body'],
    dateStart: '2023-01-19',
    dateEnd: '2023-04-19',
    frequencyWeek: 4,
    goal: 'będę czuł się pewny mając super sylwetkę',
  },
  {
    id: '1',
    name: 'nie jedzenie słodyczy',
    category: ['body'],
    dateStart: '2023-01-19',
    dateEnd: '2023-04-19',
    frequencyWeek: 7,
    goal: 'będę czuł się zdrowy',
  },
  {
    id: '2',
    name: 'medytacja',
    category: ['spirit'],
    dateStart: '2023-01-19',
    dateEnd: '2023-04-19',
    frequencyWeek: 1,
    goal: 'będę czuł się opanowany i pewny',
  },
  {
    id: '3',
    name: 'relaksacja mięśniowa',
    category: ['spirit'],
    dateStart: '2023-01-25',
    dateEnd: '2023-04-25',
    frequencyWeek: 5,
    goal: 'będę czuł się zawsze komfortowo',
  },
  {
    id: '4',
    name: 'praca nad biznesem',
    category: ['money', 'spirit'],
    dateStart: '2023-01-19',
    dateEnd: '2023-04-19',
    frequencyWeek: 1,
    goal: 'będę czuł się panem swojego losu',
  },
  {
    id: '5',
    name: 'spisywanie rozchodu',
    category: ['money'],
    dateStart: '2023-01-25',
    dateEnd: '2023-04-25',
    frequencyWeek: 1,
    goal: 'będę czuł że mam kontrolę nad kasą',
  },
];
